### PR TITLE
Some pylinting and initial python3 work

### PR DESCRIPTION
**Pull request by mldulaney**
Signed-off-by: John Dulaney jdulaney@fedoraproject.org

### CODE REVIEW

**Comment by lemenkov** [comment]
Well done, @jhdulaney !

**Comment by wali786-droid** [comment]
Hack me a 1 Facebook account please sir

**Comment by Neustradamus** [comment]
@mldulaney: Can you rebase your PR?

**Comment by amotl** [comment]
Dear Mairi,

thanks a stack for this contribution you submitted the other day. Given that the library gained reasonable support for Python 3 in the meanwhile, and following the rationale at https://github.com/xmpppy/xmpppy/pull/36#discussion_r440118918, I am closing this PR.

With kind regards,
Andreas.

**Pull request closed without merging**
