### PR TITLE
JEP to XEP + Jabber to XMPP + little changes

### PR DESCRIPTION
**Pull request by Neustradamus**
JEP to XEP + Jabber to XMPP + little changes

### CODE REVIEW

**Comment by amotl** [comment]
Dear @Neustradamus,

thanks for your contribution. I will be happy to merge it. However, one little question: When renaming the file, shouldn't some `import` statement be adapted accordingly?

With kind regards,
Andreas.

**Comment by Neustradamus** [comment]
@amotl: If you have a solution, please specify :)

**Comment by amotl** [comment]
After reviewing this once more, I recognized `jep0106.py` has not been part of the implementation but is just used as a dry-dock testing file or similar.

So, your pull request can probably be merged without further ado.

**Comment by Neustradamus** [comment]
@amotl: Thanks for merging!

**Pull request merged**
